<html>
<head>
    <meta charset="UTF-8">
    <title>JBusters</title>
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

</head>
<body>
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Ups..😫</h1>
        <h2>Cos poszło nie tak..</h2>
        <p>Musisz podać liczbę dodatnią lub 0</p>
        <hr class="my-4">
        <#--<button class="btn btn-primary" href="/aplikacja">Spróbuj ponownie</button>-->
        <a class="btn btn-primary" href="index.html">Spróbuj ponownie</a>
            </tbody>
        </table>
    </div>

</div>


<footer>&copy; 2018-2019 Tomek Ociepa</footer>
<script src="js/jquery-3.3.1.slim.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>